Repository kubevirt/macvtap-cni, pull requests merged in 2020-09, with the labels that each got.

#25 Change vbom.ml/util dependeny with github.com/fvbommel/util
  go.mod
  go.sum
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#24 Adding quotes in macvtap.yaml.in
  hack/generate-manifests.sh
  templates/macvtap.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#26 Release v0.3.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#27 Fix container command quotes in macvtap.yaml.in
  templates/macvtap.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#28 Release v0.3.1
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#31 Release v0.4.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
