Repository kubevirt/macvtap-cni, pull requests merged in 2020-03, with the labels that each got.

#7 Functests
  Makefile
  automation/check-patch.e2e-k8s.sh
  cluster/kubevirtci.sh
  cluster/sync.sh
  go.mod
  hack/functest.sh
  tests/e2e/e2e_suite_test.go
  tests/e2e/macvtap_test.go
  tests/e2e/tests.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#9 Add README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#12 Push images to quay on successful CI executions
  Makefile
  automation/publish.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#13 Fix issues preventing image generation
  automation/check-patch.setup.sh
  automation/publish.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#16 Generate a release via `make release`
  Makefile
  automation/release.sh
  hack/version.sh
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#17 Add prepare release scripts
  Makefile
  hack/bump-version.sh
  hack/prepare-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#18 ci: release also to github
  Makefile
  automation/check-patch.setup.sh
  go.mod
  go.sum
  hack/release.sh
  tools.go
  vendor/github.com/aktau/github-release/.gitignore
  vendor/github.com/aktau/github-release/LICENSE
  vendor/github.com/aktau/github-release/Makefile
  vendor/github.com/aktau/github-release/README.md
  vendor/github.com/aktau/github-release/assets.go
  vendor/github.com/aktau/github-release/cmd.go
  vendor/github.com/aktau/github-release/commit.go
  vendor/github.com/aktau/github-release/error.go
  vendor/github.com/aktau/github-release/github-release.go
  vendor/github.com/aktau/github-release/github/debug.go
  vendor/github.com/aktau/github-release/github/file.go
  vendor/github.com/aktau/github-release/github/github.go
  vendor/github.com/aktau/github-release/releases.go
  vendor/github.com/aktau/github-release/tags.go
  vendor/github.com/aktau/github-release/term.go
  vendor/github.com/aktau/github-release/util.go
  vendor/github.com/aktau/github-release/version.go
  vendor/github.com/dustin/go-humanize/.travis.yml
  vendor/github.com/dustin/go-humanize/LICENSE
  vendor/github.com/dustin/go-humanize/README.markdown
  vendor/github.com/dustin/go-humanize/big.go
  vendor/github.com/dustin/go-humanize/bigbytes.go
  vendor/github.com/dustin/go-humanize/bytes.go
  vendor/github.com/dustin/go-humanize/comma.go
  vendor/github.com/dustin/go-humanize/commaf.go
  vendor/github.com/dustin/go-humanize/ftoa.go
  vendor/github.com/dustin/go-humanize/humanize.go
  vendor/github.com/dustin/go-humanize/number.go
  vendor/github.com/dustin/go-humanize/ordinals.go
  vendor/github.com/dustin/go-humanize/si.go
  vendor/github.com/dustin/go-humanize/times.go
  vendor/github.com/tomnomnom/linkheader/.gitignore
  vendor/github.com/tomnomnom/linkheader/.travis.yml
  vendor/github.com/tomnomnom/linkheader/CONTRIBUTING.mkd
  vendor/github.com/tomnomnom/linkheader/LICENSE
  vendor/github.com/tomnomnom/linkheader/README.mkd
  vendor/github.com/tomnomnom/linkheader/main.go
  vendor/github.com/voxelbrain/goptions/.gitignore
  vendor/github.com/voxelbrain/goptions/CHANGELOG.md
  vendor/github.com/voxelbrain/goptions/CONTRIBUTORS.md
  vendor/github.com/voxelbrain/goptions/LICENSE.txt
  vendor/github.com/voxelbrain/goptions/README.md
  vendor/github.com/voxelbrain/goptions/circle.yml
  vendor/github.com/voxelbrain/goptions/flag.go
  vendor/github.com/voxelbrain/goptions/flagset.go
  vendor/github.com/voxelbrain/goptions/goptions.go
  vendor/github.com/voxelbrain/goptions/helpfunc.go
  vendor/github.com/voxelbrain/goptions/marshaler.go
  vendor/github.com/voxelbrain/goptions/mutexgroup.go
  vendor/github.com/voxelbrain/goptions/options.go
  vendor/github.com/voxelbrain/goptions/special_types.go
  vendor/github.com/voxelbrain/goptions/tagparser.go
  vendor/github.com/voxelbrain/goptions/valueparser.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#19 Release v0.1.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#20 Unify template manifest
  Makefile
  hack/generate-manifests.sh
  manifests/macvtap.yaml
  manifests/namespace.yaml
  manifests/scc.yaml
  templates/macvtap.yaml.in
  templates/namespace.yaml.in
  templates/scc.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
