Repository kubevirt/macvtap-cni, pull requests merged in 2022-05, with the labels that each got.

#70 podman: Use quay full image name
  cmd/Dockerfile
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#71 Bump golang1.17
  automation/check-patch.setup.sh
  cmd/Dockerfile
  go.mod
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-stack/stack/go.mod
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/mattn/go-colorable/go.mod
  vendor/github.com/mattn/go-colorable/go.sum
  vendor/github.com/mattn/go-isatty/go.mod
  vendor/github.com/mattn/go-isatty/go.sum
  vendor/github.com/nxadm/tail/go.mod
  vendor/github.com/nxadm/tail/go.sum
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/github.com/vishvananda/netlink/go.mod
  vendor/github.com/vishvananda/netlink/go.sum
  vendor/github.com/vishvananda/netns/go.mod
  vendor/github.com/vishvananda/netns/go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/xerrors/go.mod
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
Labels: dco-signoff: yes, release-note, size/XL, approved, lgtm

#66 config, scc: add volume parameter
  templates/scc.yaml.in
Labels: dco-signoff: yes, release-note, size/XS, approved, lgtm
