Repository kubevirt/macvtap-cni, pull requests merged in 2022-10, with the labels that each got.

#81 Release v0.9.0
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#79 Fix nil pointer error for k8s 1.25
  pkg/deviceplugin/plugin.go
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm, needs-ok-to-test

#82 device plugin: fix registration order for k8s-1.25
  go.mod
  go.sum
  vendor/github.com/kubevirt/device-plugin-manager/pkg/dpm/plugin.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/S, release-note, approved, lgtm

#83 e2e tests: print network status annotation on error
  tests/e2e/macvtap_test.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#84 Release v0.10.0
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#86 e2e, multi-net: use non-deprecated network-status annot
  tests/e2e/macvtap_test.go
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#87 Release v0.10.1
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm
