Repository kubevirt/macvtap-cni, pull requests merged in 2022-04, with the labels that each got.

#60 ci: bump kubevirtci to 1.21
  automation/check-patch.e2e-k8s.sh
  cluster/cluster.sh
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#58 Fix the NetworkAttachmentDefinition example
  README.md
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm, ok-to-test

#62 ci: use golang-1.16
  automation/check-patch.setup.sh
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#63 config, scc: add required parameters
  templates/scc.yaml.in
Labels: dco-signoff: yes, release-note, size/XS, approved, lgtm

#64 Release v0.7.0
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm
