Repository kubevirt/macvtap-cni, pull requests merged in 2022-02, with the labels that each got.

#55 githug: add release note to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#53 Typo in configuration sample
  README.md
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm, ok-to-test

#56 Release v0.6.1
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm
